from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError
from dotenv import load_dotenv
import os
import time
from typing import Dict, Any, List

from backend.models import AnalyzeRequest, AnalyzeResponse, Insight
from backend.exceptions import InsightError, InvalidContentError, AIServiceError
from backend.agents import PlannerAgent, ExpertAgent

# Load environment variables
load_dotenv()

# Initialize FastAPI app
app = FastAPI(
    title="AI Insight Widget API",
    description="API for the AI Insight Widget that analyzes webpage content",
    version="0.1.0"
)

# Initialize AI agents
planner_agent = PlannerAgent()
expert_agent = ExpertAgent()

# Demo mode configuration
DEMO_MODE = os.getenv("DEMO_MODE", "false").lower() == "true"

# Sample insights for demo mode
SAMPLE_INSIGHTS = [
    {
        "content": "Simplify complex concepts using analogies and simpler language.",
        "rationale": "The current content uses technical terms like 'neural networks' without simplification, which may confuse non-experts. Using analogies, like comparing neural networks to brain cells, can make the content more accessible.",
        "impact": "High"
    },
    {
        "content": "Include specific, everyday examples of AI in action.",
        "rationale": "While the content mentions broad applications like autonomous vehicles, adding specific examples such as AI in voice assistants or recommendation systems would better illustrate AI's role in daily life.",
        "impact": "High"
    },
    {
        "content": "Expand on ethical considerations with real-world scenarios.",
        "rationale": "The content mentions ethical issues but lacks depth. Expanding on scenarios like biased algorithms in hiring can make these considerations more relatable and pressing for the audience.",
        "impact": "Medium"
    },
    {
        "content": "Incorporate expert quotations or statistics on AI impacts.",
        "rationale": "Including insights from leading AI experts or statistics about AI's impact, such as job displacement rates, can lend credibility and depth to the content.",
        "impact": "Medium"
    },
    {
        "content": "Discuss future trends with potential positive and negative outcomes.",
        "rationale": "While the content predicts increased AI integration, it should also explore potential outcomes like the balance between automation and human jobs, or privacy enhancements vs. invasions.",
        "impact": "High"
    }
]

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=os.getenv("ALLOWED_ORIGINS", "http://localhost:3000").split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.exception_handler(InsightError)
async def insight_error_handler(request: Request, exc: InsightError) -> JSONResponse:
    """Handle custom insight errors."""
    return JSONResponse(
        status_code=exc.status_code,
        content={
            "error": {
                "code": exc.error_code,
                "message": exc.detail,
                "additional_info": exc.additional_info
            }
        }
    )

@app.exception_handler(RequestValidationError)
async def validation_error_handler(request: Request, exc: RequestValidationError) -> JSONResponse:
    """Handle request validation errors."""
    return JSONResponse(
        status_code=422,
        content={
            "error": {
                "code": "VALIDATION_ERROR",
                "message": "Invalid request parameters",
                "details": exc.errors()
            }
        }
    )

@app.get("/health")
async def health_check() -> Dict[str, str]:
    """Health check endpoint to verify the API is running."""
    return {
        "status": "healthy",
        "version": "0.1.0",
        "demo_mode": DEMO_MODE
    }

def get_demo_insights() -> List[Insight]:
    """Return sample insights for demo mode."""
    return [Insight(**insight) for insight in SAMPLE_INSIGHTS]

@app.post("/analyze", response_model=AnalyzeResponse)
def analyze_content(request: AnalyzeRequest) -> AnalyzeResponse:
    """
    Analyze webpage content and return insights.
    
    This endpoint processes the provided content through our AI pipeline:
    1. Content is analyzed by the planner agent
    2. Insights are generated by the expert agent
    
    If DEMO_MODE is enabled, it returns sample insights instead of calling AI services.
    """
    start_time = time.time()
    
    # Use demo mode if enabled
    if DEMO_MODE:
        return AnalyzeResponse(
            insights=get_demo_insights(),
            expert_role="Content Strategist",
            processing_time=time.time() - start_time
        )
    
    try:
        # Step 1: Use planner to determine expert and approach
        plan = planner_agent.analyze_content(
            content=request.content,
        )
        
        # Step 2: Get insights from the expert
        expert_insights = expert_agent.generate_insights(
            content=request.content,
            expert_role=plan["expert_role"],
            analysis_prompt=plan["analysis_prompt"],
            focus_areas=plan["focus_areas"],
        )
        
        # Step 3: Convert expert insights to response format
        insights = [
            Insight(
                content=insight["content"],
                rationale=insight["rationale"],
                impact=insight["impact"]
            )
            for insight in expert_insights
        ]
        
        return AnalyzeResponse(
            insights=insights,
            expert_role=plan["expert_role"],
            processing_time=time.time() - start_time
        )
        
    except Exception as e:
        raise AIServiceError(str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "main:app",
        host=os.getenv("HOST", "0.0.0.0"),
        port=int(os.getenv("PORT", "8000")),
        reload=True
    ) 